spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kg?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhenghao2
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 100
      maximum-pool-size: 100
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/

server:
  tomcat:
    uri-encoding: utf-8
    max-connections: 10000
  servlet:
   encoding:
     charset: utf-8
     force: true
     enabled: true